version: 2

sources:
  - name: jaffle_shop
    database: jaffle_shop
    schema: raw
    tables: 
      - name: customers
        description: stores one order per customer
      - name: orders
        description: stores one record per order. Includes cancelled and deleted orders
        
    

